### ISSUE TITLE
Produce tasks

### ISSUE THREAD

**Issue by JakobTopholt** [TimMo-dev/P7#100]
Produce at least 3 tasks for each language such as, "Hello, World!" , make a pyhagoras solver and tell how many days are in a month based on giving a date

The should have a title, a description and state what is tested for to verify completion.

Tasks should contain:

numbers (from 0-N, where the first task is 0)
A language acossiated with it
a description
An example
A number of tests to verify the solution
Potentially template code setup.

**Comment by ZumzarHS** [comment]
Task har ikke en test eller sprog knyttet dertil. Tænker det kan tilføjes i et andet issue
