### ISSUE TITLE
Database connection and data retrieval

### ISSUE THREAD

**Issue by JakobTopholt** [TimMo-dev/P7#102]
In order to retrieve and send data from the database, we have to setup the connection and define the different endpoints. This will be done using typeORM.

**Comment by TimMo-dev** [comment]
i'm going to adapt existing database implementations to typeorM :)

**Comment by TimMo-dev** [comment]
It took 3 weeks to complete this task. The following changes has been made. 

- Typeorm has been added to handle database related operations. 
- Models/tables has been defined properly. Using TypeOrm will make testing and making changes faster and easier.
-A rudimentary seeder has been added to create testdata for the database. It currently wipes the whole database to insert its own data, and is thus a bad solution. This works for now, but there is better ways. 
- tsconfig.json has been changed to accomodate typeORM. I have no idea what 80% of the configurations do, but it works so it will have to suffice.

**Comment by TimMo-dev** [comment]
Current implementations have been adapted in #115
