### ISSUE TITLE
Rewrite task descriptions

### ISSUE THREAD

**Issue by mpmunch** [TimMo-dev/P7#110]
The task descriptions should be clear and concise.  
A task description should provide:

- The goal for the task (e.g. "sum two variables")
- A description of predefined variables (e.g. "two int variables  'a' and 'b' will be provided with predefined values)
- The expected output (e.g. "the function should print the sum of 'a' and 'b' in a console.log")

An example of a  possible task description:

> Reverse a given string. 
> The variable "example_string" has a predefined value and should be used. Print the reversed variable.

**Comment by JakobTopholt** [comment]
All the rewrites can be found on branch 110.

**Comment by JakobTopholt** [comment]
Now coupled with #113
