### ISSUE TITLE
Write about Project Management

### ISSUE THREAD

**Issue by mpmunch** [TimMo-dev/P7#21]
Write about the project management of the report. Is Related to #12 
Should be pretty easy to just copy from #12. 

- [ ] A section about tools used such as GitHub, GitHub Boards
- [ ] Write about about the agile workflow

**Comment by JakobTopholt** [comment]
This is basically done

**Comment by ZumzarHS** [comment]
Har rettet det lidt til og fjernet Test Driven Development og Continuos Integration afsnittene da vi ikke har brugt det. En anden må gerne lige læse i gennem og se om de er enig i at det er done

**Comment by CHSten** [comment]
sounds good. Har reviewet den
