### ISSUE TITLE
Choose how feedback should be provided

### ISSUE THREAD

**Issue by ZumzarHS** [TimMo-dev/P7#26]
Description: Write a small section on 'how to teach beginners' which acts as a link between the "Ideal Programming Tasks for Beginners" and "Programming Languages in Learning Coding"

Use knowledge from sections "Feedback" and "Ideal tasks.." to write a section where it explores how the program should provide feedback. 
Key point from Feedback sections: Combination of advantages from written and verbal feedback.
Key point from Programming Tasks: Simple exercises and not bigger programs. 

This task could be supported by a survey.

Acceptance Criteria:
- [ ] Research how to teach beginners (not feedback related)
- [x] Write the section
- [ ] Review

**Comment by JakobTopholt** [comment]
@CHSten jeg kan ikke finde hvor det her er skrevet :(((((
