### ISSUE TITLE
Decide on a Testing Suite

### ISSUE THREAD

**Issue by JakobTopholt** [TimMo-dev/P7#46]
Description: There are several testing suites out there, we should figure out which one to use.

Acceptance Criteria:
- [x] Decide on a testing suite
- [x] Discuss with group
- [x] Write about it in technologies
- [x] Review

**Comment by CHSten** [comment]
fik sammenlignet Jest, Mocha og Vitest og konkluderet at vi vælger Vitest (som vi allerede bruger :) )
