### ISSUE TITLE
Do Prompt Engineering

### ISSUE THREAD

**Issue by JakobTopholt** [TimMo-dev/P7#51]
Description: Do prompt engineering on what ever the chosen LLM is. Find a way to formulate a prompt in which the LLM behaves consistently and as intended. Write about the methods and final prompt chosen for the LLM

Acceptance Criteria:
- [x] Do prompt engineering
- [x] Write about prompt engineering method and final prompt
- [x] Review

User Story: As a group member i want to do prompt engineering so that the LLM returns a appropriate feedback to the user

**Comment by CHSten** [comment]
Har lavet og skrevet om prompt engineering (første draft). Den enedelig system prompt ligger i Appendix A i overleaf
