### ISSUE TITLE
Write about Kubernetes in a technology chapter

### ISSUE THREAD

**Issue by JakobTopholt** [TimMo-dev/P7#53]
Description: We should explain our interest in using Kubernetes, for scalability purposes, in the report. If we start doing a little bit of it, this should also be initialized in the implementation chapter.

Acceptance Criteria:
- [x] Do a bit of research and source-finding
- [x] Write about Kubernetes, in technologies.
- [ ] Review

**Comment by ZumzarHS** [comment]
Har reviewet og tilføjet en række kommentarer. Hvis der er tvivl om hvad jeg mener med kommentarerne så spørg.

**Comment by JakobTopholt** [comment]
Someone else should go through this again, and pick a side when it comes to resolving comments.
