### ISSUE TITLE
Rewrite class section

### ISSUE THREAD

**Issue by TimMo-dev** [TimMo-dev/P7#57]
Description: 
Rewrite the class diagram and its section. Must be remade per Peter Dologs review.

Is related to #29 

AC: 

- [ ] The class diagram has been remade, with more granularity. 
- [ ] Its associated description has been rewritten to reflect the change. 

>[!NOTE]
> The section has been written in 3.1

**Comment by JakobTopholt** [comment]
Jeg reviewer lige den.

**Comment by JakobTopholt** [comment]
Looks really nice.

**Comment by TimMo-dev** [comment]
Skal rettes igen per Peter Dologs rettelser
