### ISSUE TITLE
Refine the rich text editor

### ISSUE THREAD

**Issue by JakobTopholt** [TimMo-dev/P7#62]
The "sandbox" , "IDE" , "Development" or what you want to call it, should resemble taking code as its input to a greater extend. Additionally add a couple of sentences to 'Solution-Page' under the 'Implementation' Chapter about the implementation.

For this to be achieved the the checkboxes below should be completed. 

This extends issue #48.

- [x] Line numbers are showcased.
- [x] Syntax highlighting is present
- [x] Syntax higlights Python
   - [x] Is expandable to more programming languages
- [x] Write about it in the implementation chapter 
- [x]  Review

**Comment by CHSten** [comment]
lavet pull-req med en IDE i 'Code Block' på solution page som er samme IDE som VS code bruger. Har skrevet en lille sjat til det i solution-page subsectionen i Implementations kapitlet

**Comment by JakobTopholt** [comment]
Jeg review'er den lige.

**Comment by JakobTopholt** [comment]
Looks great, jeg efterlod nogle track changes kommentarer i rapporten, som jeg antager at du er enig med. så jeg approver lige :)
