### ISSUE TITLE
frontend: make language option

### ISSUE THREAD

**Issue by TimMo-dev** [TimMo-dev/P7#63]
Make it possible to choose between different programming languages in the front-end. This should ideally be a drop down  menu.
Currently there is only one language to choose from.

AC: 
- [ ] A widget with selectable options. 
- [ ] The selected language is sent to the backend, along with the code.

**Comment by ZumzarHS** [comment]
Mangler at lave test til det, men derudover skulle valg af programmeringssprog gerne være done. Valg af sprog(Dansk, Engelsk) er også sat ind frontend mæssigt, men er ikke koblet til backend da det ikke var en del af dette issue alligevel.

Branchen hedder "LanguageOptions"

**Comment by JakobTopholt** [comment]
Jeg kigger på den, jeg opdager det nok hurtigt, men er det meningen at der også implementeres et nyt sprog, eller bare at man kan vælge andet?

Anyhow, some skrevet opdager jeg det nok hurtigt.

**Comment by JakobTopholt** [comment]
@ZumzarHS Mangler indikator for at knappen er drop down.

Men ellers Lgtm.

**Comment by JakobTopholt** [comment]
Fuck being scrollable.

**Comment by ZumzarHS** [comment]
Der er lavet ændringer således valget af programmeringssprog bliver sendt til backend sammen med koden der er indtastet i CodeArea så snart der bliver trykket Submit.
Desuden er der implementeret noget Tailwind CSS

**Comment by JakobTopholt** [comment]
Me review

**Comment by JakobTopholt** [comment]
Please inform reviewers of which packages should be installed 🤓 

npm install @headlessui/vue

**Comment by JakobTopholt** [comment]
> valget af programmeringssprog bliver sendt til backend sammen med koden der er indtastet i CodeArea så snart der bliver trykket Submit.

Er der ikke et problem hvis man vil have syntax highlighting some reflekterer sproget man skriver i?
