### ISSUE TITLE
Make response from backend visible on website

### ISSUE THREAD

**Issue by TimMo-dev** [TimMo-dev/P7#69]
The website sends the code submission as a request to the server, where the response is send back as a header with the results from the container. The results need to be visible on the UI on the website. 

AC: 

- [x] An extra box with terminal output has been made on the website
- [x] The response is formatted properly

**Comment by ZumzarHS** [comment]
Output fra terminalen kommer i feedback boksen nederst på siden. Der bliver desuden tjekket om der er en fejl i koden, hvis der er det bliver det udskrevet.

**Comment by ZumzarHS** [comment]
Output kommer nu i en output div i stedet. Der er også tilføjet resizeable panels mellem de to divs i bunden

**Comment by JakobTopholt** [comment]
@ZumzarHS A PR?😳  👉🏻 👈🏻 

Makes it a bit nicer to review.
