### ISSUE TITLE
Restructure project folders

### ISSUE THREAD

**Issue by TimMo-dev** [TimMo-dev/P7#75]
The current project folder structure is very messy and needs to be cleaned up. 
Consulting with chatgpt gives this suggestion of project structure: 
```
project-root/
│
├── docs/
│   ├── README.md
│   ├── API-specifications/
│   ├── Tutorials/
│   └── Design/
│
├── src/
│   ├── programming-learning-language/
│   │   ├── Python/
│   │   ├── JavaScript/
│   │   ├── Java/
│   │   └── README.md
│   ├── server/
│   │   ├── app/
│   │   ├── config/
│   │   └── Dockerfile
│   └── python-interpreter/
│       ├── interpreter_code/
│       └── tests/
│
├── config/
│   ├── docker/
│   │   └── Dockerfile
│   └── env/
│       ├── dev.env
│       ├── prod.env
│       └── test.env
│
├── tests/
│   ├── unit/
│   ├── integration/
│   └── e2e/
│
├── scripts/
│   ├── setup/
│   └── maintenance/
│
└── .gitignore

```

AC: 

- [ ] The project folder structure has been revamped.
- [ ] Everything still works, this includes packages and dependencies.
- [ ] any paths are still pointing to the right place.

**Comment by JakobTopholt** [comment]
I think I'll draw inspiration from this
![Image](https://github.com/user-attachments/assets/867f9617-1037-4df4-b2a4-36bfd5102ea4)
https://practicalseries.com/1001-webdevelopment/04-02-starting.html

**Comment by JakobTopholt** [comment]
@TimMo-dev do you consider "programming-learning-tool" not being a "master folder" in lack of a better term, an important thing?

**Comment by TimMo-dev** [comment]
@JakobTopholt @mpmunch blev vi enige om at sætte denne opgave på hold?

**Comment by JakobTopholt** [comment]
@TimMo-dev @mpmunch Jeg er ikke sikker på om vi blev enige i at sætte den på hold.

Men jeg synes at det ville være en god ide at sætte den på hold.
