### ISSUE TITLE
Create a page for selecting coding tasks

### ISSUE THREAD

**Issue by mpmunch** [TimMo-dev/P7#84]
A page should be created where it is possible to select the coding language and a task. See figure 4.3 in Overleaf.

Might rely on issue #50 

- [x] A first iteration of the task selection page using tailwind and vue
- [ ] The page should redirect back to the solution page with the selected task in the description field.

**Comment by CHSten** [comment]
Lavede taskspage og skrev om det i implementation kapitlet (Tilføjede også horzontal og vertical split-panels)

**Comment by ZumzarHS** [comment]
Reviewede koden til dette issue da jeg koblede db og task sammen. Looks good. Teksten på overleaf er også fin.
